apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      # version: "4.10.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-values-cm
