providers:
  default: azureOpenAI
  azureOpenAI:
    # apiKey: ""
    apiKeySecretKey: AZUREOPENAI_API_KEY
    apiKeySecretRef: kagent-azure-openai
    config:
      apiVersion: "2024-12-01-preview"
      # azureAdToken: ""
      azureDeployment: "gpt-4o-mini"
      azureEndpoint: "https://olegen.openai.azure.com/"
    model: gpt-4o-mini
    provider: AzureOpenAI