apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/configs/eso
  - ../../../base/configs/cert-manager

patches:
  - path: patches/store.yaml
    target:
      name: kv-olegen
      kind: ClusterSecretStore
