apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/tenant: d1-blue
spec:
  interval: 1h
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlay/d1-blue
  wait: true
  prune: true
  timeout: 5m0s
