apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.8.1"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: oauth2-proxy-values-cm
