apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xresourcegroups.azure.infra.dcp.sap
spec:
  group: azure.infra.dcp.sap
  names:
    kind: XResourceGroup
    plural: xresourcegroups
  claimNames:
    kind: ResourceGroup
    plural: resourcegroups
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
            required:
            - name