---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-values-cm
---