apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kagent-ingress
  namespace: kagent
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - "*.gitops.olegen.fun"
    - "gitops.olegen.fun"
    secretName: le-cert-wildcard
  rules:
  - host: kagent.gitops.olegen.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kagent
            port:
              number: 80
  ingressClassName: nginx