apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/flux-ui
  - flux-ui-ingress.yaml
  - ../../base/oauth2-proxy
  - ./mcp/crawl4ai-rag
  - ./mcp/flux-mcp-server
