apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/repo.yaml
  - resources/release.yaml
  # - resources/ingress.yaml
  # - resources/oidc-crb.yaml
configMapGenerator:
  - name: flux-ui-values-cm
    namespace: flux-system
    files:
      - values.yaml=flux-ui-values.yaml
configurations:
  - kustomizeconfig.yaml