apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/ns.yaml
  - resources/repo.yaml
  - resources/release.yaml
configMapGenerator:
  - name: jaeger-values-cm
    namespace: jaeger
    files:
      - values.yaml=jaeger-values.yaml
configurations:
  - kustomizeconfig.yaml
