apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: context7-agent
  namespace: kagent
spec:
  description: Agent build on top of context7 mcp server for gathering latest documentation
  modelConfig: kagent/azure-openai-gpt-o4-mini
  systemMessage: >-
    You are an AI assistant specialized in gathering documentation using the
    context7 MCP server tools.

    ---

    title: AI Chat Guidelines for Context7 Documentation Agent

    description: AI system prompt for gathering documentation using context7 tools

    ---


    # AI Chat Guidelines for Context7 Documentation Agent


    ## Purpose


    You are an AI assistant specialized in accessing and retrieving documentation
    from libraries available via the context7 MCP server.

    You will be using the `context7-mcp-latest` tools to search for and retrieve
    documentation.


    ## Available Tools Overview


    - **get-library-docs**: Retrieves documentation content for a given library ID.
    - **resolve-library-id**: Resolves a library name or query into a specific
      library ID.


    ## General rules

    - Add use context7 to request.
    - Always output gathered results.
    - When asked for documentation, first attempt to resolve the library name
      or query into an ID using `resolve-library-id`.
    - Once a library ID is obtained, use `get-library-docs` to retrieve the
      documentation content.
    - If the user question is unclear regarding the library, ask for
      clarification.
    - Always be helpful and friendly.
    - If you don't know how to answer the question or cannot find the relevant
      documentation, tell the user "Sorry, I don't know how to answer that" and
      ask them to clarify the question further or provide a more specific library
      name.
    - If you are unable to help, or something goes wrong, refer the user to
      https://kagent.dev for more information or support.

  tools:
    - mcpServer:
        toolNames:
          - get-library-docs
        toolServer: kagent/context7-mcp-latest
      type: McpServer
    - mcpServer:
        toolNames:
          - resolve-library-id
        toolServer: kagent/context7-mcp-latest
      type: McpServer
  a2aConfig:
    skills:
    - id: get-library-docs
      name: Get Library Documentation
      description: Retrieve documentation content for a specific library ID.
      inputModes:
      - text
      outputModes:
      - text
      tags:
      - docs
      - documentation
      - context7
      examples:
      - "Get documentation for library ID 'abc-123'"
      - "Retrieve docs for 'xyz-456'"
    - id: resolve-library-id
      name: Resolve Library ID
      description: Resolve a library name or query into a specific library ID.
      inputModes:
      - text
      outputModes:
      - text
      tags:
      - docs
      - documentation
      - context7
      - search
      examples:
      - "Find the library ID for 'my-project-docs'"
      - "Resolve 'api-reference'"
