IyBJbnRlbnRpb25hbGx5IGZhaWxpbmcgRmx1eCBIZWxtUmVsZWFzZSArIEhlbVJlcG9zaXRvcnkgZm9yIHRlc3RpbmcKIyBBcHBseSB3aXRoOiBrdWJjdGwgYXBwbHkgLWYgZmFpbGluZy1oZWxtcmVsZWFzZS55YW1sCmlzdWJHZXQ6IHNvdXJjZWxpbmUtbmFtZTogc29tZS1jb2RlCmlhc2RmczoKICAtIGF1dGg6IHN0dWRvIHJlYWQK
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: komodorio
  namespace: test
  annotations:
    kagentFix: "2025-09-17T08:58:30Z"
spec:
  interval: 1h0m0s
  url: https://helm-charts.komodor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: komoplane-20
  namespace: test
  annotations:
    kagentFix: "2025-09-17T08:58:30Z"
spec:
  interval: 5m
  chart:
    spec:
      chart: komoplane
      sourceRef:
        kind: HelmRepository
        name: komodorio
  values:
    replicaCount: 1
---