apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/ns.yaml
  - resources/repo.yaml
  - resources/release.yaml
configMapGenerator:
  - name: external-secrets-values-cm
    namespace: external-secrets
    files:
      - values.yaml=external-secrets-values.yaml
configurations:
  - kustomizeconfig.yaml
