apiVersion: azure.infra.dcp.sap/v1alpha1
kind: Cluster
metadata:
  name: d1-blue
  namespace: default
  labels:
    env: d1
spec:
  name: d1-blue
  rgName: gitops-example
  kubernetesVersion: 1.31.2
  dnsName: olegen.fun
  nodePool:
    nodeCount: 2
    maxPods: 200
    name: pool
    vmSize: Standard_A2_v2
    osDiskSizeGb: 128
    vnetSubnetIdRef: d1-blue-aks-snet
