apiVersion: workload.dcp.sap/v1alpha1
kind: FluxOperator
metadata:
  name: d1-blue-aks-flux-operator
  namespace: default
  labels:
    env: d1
spec:
  name: d1-blue
  rgName: gitops-example
  flux:
    url: https://github.com/olegenii/gitops-example
    version: 2.5.x
    branch: main
    secretRef:
      name: es-flux-system
      namespace: crossplane-system
