# external-secrets managed identity  related values
podLabels:
  azure.workload.identity/use: "true"
serviceAccount:
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "796e3a57-16df-4a5b-b170-56380cf4fb21"
    azure.workload.identity/tenant-id: "bd60af36-5e42-4c11-ab8a-55400b1491fe"
