apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/ns.yaml
  - resources/repo.yaml
  - resources/release.yaml
  - resources/es-oauth2-proxy-github-oidc.yaml
configMapGenerator:
  - name: oauth2-proxy-values-cm
    namespace: oauth2-proxy
    files:
      - values.yaml=oauth2-proxy-values.yaml
configurations:
  - kustomizeconfig.yaml
