config:
  existingSecret: oauth2-proxy-github-oidc
  configFile: |-
    provider = "github"
    email_domains = [ "*" ]  # Or limit to your org, e.g., ["yourdomain.com"]
    cookie_secure = true
    # cookie_httponly = true
    # cookie_samesite = "lax"
    github_org = "gitops-example-olegenii"  # Optional, to restrict to members
    # github_team = "<your-team>"  # Optional, to restrict to a specific team
    redirect_url = "https://kagent.d1.gitops.olegen.fun/oauth2/callback"
    scope = "user:email read:org"
    upstreams = [ "file:///dev/null" ]
ingress:
  enabled: true
  path: /oauth2
  hosts:
    - kagent.d1.gitops.olegen.fun
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/proxy-body-size: "2000m"
    # nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - secretName: letsencrypt-prod
      hosts:
        - kagent.d1.gitops.olegen.fun
        