apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/ns.yaml
  - resources/repo.yaml
  - resources/release.yaml
configMapGenerator:
  - name: ingress-nginx-values-cm
    namespace: ingress-nginx
    files:
      - values.yaml=ingress-nginx-values.yaml
configurations:
  - kustomizeconfig.yaml
