apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/ns.yaml
  - resources/repo.yaml
  - resources/release.yaml
configMapGenerator:
  - name: crossplane-values-cm
    namespace: crossplane-system
    files:
      - values.yaml=crossplane-values.yaml
configurations:
  - kustomizeconfig.yaml
