apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: jaeger
spec:
  interval: 30m
  chart:
    spec:
      chart: jaeger
      # version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: jaeger
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: jaeger-values-cm
