apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: d1-vnet
spec:
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: westeurope
    resourceGroupName: gitops-example
    # resourceGroupNameRef:
    #   name: d2
    tags:
      provisioner: crossplane
  providerConfigRef:
    name: olegen-lab