apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-openai
  namespace: kagent
spec:
  dataFrom:
  - extract:
      key: azure-openai-gpt-api-keys-mimic
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-olegen
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: kagent-openai
