apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: azure-openai-gpt-o4-mini
  namespace: kagent
spec:
  apiKeySecretKey: o4_mini
  apiKeySecret: kagent-azure-openai
  azureOpenAI:
    apiVersion: 2025-01-01-preview
    azureDeployment: o4-mini
    azureEndpoint: https://olegen.openai.azure.com/
  model: o4-mini
  provider: AzureOpenAI
