apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: azure-openai-gpt-o4-mini
  namespace: kagent
spec:
  apiKeySecretKey: o4_mini
  apiKeySecretRef: kagent-azure-openai
  azureOpenAI:
    apiVersion: 2024-12-01-preview
    azureDeployment: o4-mini
    azureEndpoint: https://olegen.openai.azure.com/
  model: o4-mini
  provider: AzureOpenAI
