apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/repo.yaml
  - resources/release.yaml
  # - resources/ingress.yaml
configMapGenerator:
  - name: komoplane-values-cm
    namespace: crossplane-system
    files:
      - values.yaml=komoplane-values.yaml
configurations:
  - kustomizeconfig.yaml
